#### Feature Creation and Extraction

##### Why Generate Features

In [1]:
import pandas as pd

data = pd.read_csv("./datasets/combined_DS_v10.csv")

In [2]:
data.head()

,SurveyDate,FormalEducation,ConvertedSalary,Hobby,Country,StackOverflowJobsRecommend,VersionControl,Age,Years Experience,Gender,RawSalary
0,2/28/18 20:20,Bachelor's degree (BA. BS. B.Eng.. etc.),NaN,Yes,South Africa,NaN,Git,21,13,Male,NaN
1,6/28/18 13:26,Bachelor's degree (BA. BS. B.Eng.. etc.),70841.0,Yes,Sweeden,7.0,Git;Subversion,38,9,Male,"70,841.00"
2,6/6/18 3:37,Bachelor's degree (BA. BS. B.Eng.. etc.),NaN,No,Sweeden,8.0,Git,45,11,NaN,NaN
3,5/9/18 1:06,Some college/university study without earning ...,21426.0,Yes,Sweeden,NaN,Zip file back-ups,46,12,Male,"21,426.00"
4,4/12/18 22:41,Bachelor's degree (BA. BS. B.Eng.. etc.),41671.0,Yes,UK,8.0,Git,39,7,Male,"£41,671.00"

In [3]:
data.columns

Index(['SurveyDate', 'FormalEducation', 'ConvertedSalary', 'Hobby', 'Country',
       'StackOverflowJobsRecommend', 'VersionControl', 'Age',
       'Years Experience', 'Gender', 'RawSalary'],
      dtype='object')

In [4]:
data.dtypes

SurveyDate                     object
FormalEducation                object
ConvertedSalary               float64
Hobby                          object
Country                        object
StackOverflowJobsRecommend    float64
VersionControl                 object
Age                             int64
Years Experience                int64
Gender                         object
RawSalary                      object
dtype: object

Setect Columns with datatype integer

In [5]:
data.select_dtypes(["int"]).columns

Index(['Age', 'Years Experience'], dtype='object')

In [6]:
data.select_dtypes(["int"]).head(3)

   Age  Years Experience
0   21                13
1   38                 9
2   45                11

##### Dealing With Categorical Variables

In [7]:
# one hot encoding
one_hot_encoded = pd.get_dummies(data, columns=["Country"], prefix="OH")
print(one_hot_encoded.columns)

Index(['SurveyDate', 'FormalEducation', 'ConvertedSalary', 'Hobby',
       'StackOverflowJobsRecommend', 'VersionControl', 'Age',
       'Years Experience', 'Gender', 'RawSalary', 'OH_France', 'OH_India',
       'OH_Ireland', 'OH_Russia', 'OH_South Africa', 'OH_Spain', 'OH_Sweeden',
       'OH_UK', 'OH_USA', 'OH_Ukraine'],
      dtype='object')

In [8]:
# creating dummy variables

dummy = pd.get_dummies(data, columns=["Country"], drop_first=True, prefix="DM")
print(dummy.columns)

Index(['SurveyDate', 'FormalEducation', 'ConvertedSalary', 'Hobby',
       'StackOverflowJobsRecommend', 'VersionControl', 'Age',
       'Years Experience', 'Gender', 'RawSalary', 'DM_India', 'DM_Ireland',
       'DM_Russia', 'DM_South Africa', 'DM_Spain', 'DM_Sweeden', 'DM_UK',
       'DM_USA', 'DM_Ukraine'],
      dtype='object')

Dealing With Uncommon Categories

In [9]:
countries = data["Country"]
country_counts = countries.value_counts()
print(country_counts)

Country
South Africa    166
USA             164
Spain           134
Sweeden         119
France          115
Russia           97
UK               95
India            95
Ukraine           9
Ireland           5
Name: count, dtype: int64

In [11]:
# crate a maskk for categories that occurs less than 10 times
mask = countries.isin(country_counts[country_counts < 10].index)
countries.mask = "Other"
print(countries.value_counts())

Country
South Africa    166
USA             164
Spain           134
Sweeden         119
France          115
Russia           97
UK               95
India            95
Other            14
Name: count, dtype: int64

##### Numeric Variables

In [18]:
# Binning Columns
data["Paid_Job"] = 0
data.loc[data["ConvertedSalary"] > 0, "Paid_Job"] = 1
display(data[["ConvertedSalary", "Paid_Job"]].head())

   ConvertedSalary  Paid_Job
0              NaN         0
1          70841.0         1
2              NaN         0
3          21426.0         1
4          41671.0         1

In [27]:
# Bin countinuous variable ConvertedSalary into 5 bins
data["equal_binned"]= pd.cut(data["ConvertedSalary"], 5)
display(data[["ConvertedSalary", "equal_binned"]].head())

# specify boundaries of the bin
import numpy as np
bins = [-np.inf, 10000, 50000, 100000, 150000, np.inf]
labels = ["Very Low", "Low", "Medium", "High", "Very High"]
data["boundary_binned"] = pd.cut(data["ConvertedSalary"], bins, labels=labels)
display(data[["ConvertedSalary", "boundary_binned"]].head())

   ConvertedSalary         equal_binned
0              NaN                  NaN
1          70841.0  (-2000.0, 400000.0]
2              NaN                  NaN
3          21426.0  (-2000.0, 400000.0]
4          41671.0  (-2000.0, 400000.0]

   ConvertedSalary boundary_binned
0              NaN             NaN
1          70841.0          Medium
2              NaN             NaN
3          21426.0             Low
4          41671.0             Low